name: 'google-chat-notify'
description: 'Google Chat Notification for GitHub Actions'
author: 'amary21'
inputs:
  name:
    description: 'job name.'
    required: true
  url:
    description: 'google chat webhook url.'
    required: true
  status:
    description: 'job status.'
    required: true
  open_check_url:
    description: 'open check url.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'green'
